### ISSUE TITLE
Example should be 12 months instead of 2

### ISSUE THREAD

**Issue by j4ckcyw** [andygrove/how-query-engines-work#1]
I think there is a typo ;)

https://github.com/ballista-compute/ballista-jvm/blob/ec55780c9985ddbc3a23d64cce575522e923ac8b/jvm/examples/src/main/kotlin/ParallelQuery.kt#L31

**Comment by andygrove** [comment]
Fixed in https://github.com/andygrove/how-query-engines-work/pull/6
